# List of programming languages the user prefers to work with
preferred_language_list = [
    "rust",
    "python",
    "javascript",
    "java",
    "c++",
    "ruby",
    "go",
]

# Default editor command
editor_cmd = "zed"

# Difficulty level: can be "easy", "medium", "hard", or "all"
difficulty = "easy"